server:
  port: 1515
spring:
  application:
    name: trajefino
  datasource:
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgresdb}
    username: ${DB_USER:pgadmin}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: trajefino
        hbm2ddl.create_namespaces: true
        format_sql: true
    show-sql: true

jwt:
  secret: 642b6ffc208b37de0d72a844664dfdb839e11fec07fe90bb314cb8aaee427ef3
  expiration: 86400000